<?php

namespace Gone\Testing;

use Faker\Factory as FakerFactory;
use Faker\Generator;
use Faker\Provider;

class TestCase extends \PHPUnit\Framework\TestCase
{
	/**
	 * @see https://github.com/fzaninotto/Faker
	 *
	 * @var Generator $faker
	 */
	static private $faker;

	static public function setUpBeforeClass()
	{
		parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		self::$faker = FakerFactory::create();
		self::$faker->addProvider(new Provider\Base(self::$faker));
		self::$faker->addProvider(new Provider\DateTime(self::$faker));
		self::$faker->addProvider(new Provider\Lorem(self::$faker));
		self::$faker->addProvider(new Provider\Internet(self::$faker));
		self::$faker->addProvider(new Provider\Payment(self::$faker));
		self::$faker->addProvider(new Provider\en_US\Person(self::$faker));
		self::$faker->addProvider(new Provider\en_US\Address(self::$faker));
		self::$faker->addProvider(new Provider\en_US\PhoneNumber(self::$faker));
		self::$faker->addProvider(new Provider\en_US\Company(self::$faker));
	}


}